version: 2
jobs:
  deploy-live:
    working_directory: ~/hexarena-fe
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: Build
          command: npm run build
      - run:
          name: Upload files
          command: |
            scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./dist/* root@hexarena.io:~/hexarena/live/hexarena-fe/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-live:
          filters:
            branches:
              only: master
