version: 2
jobs:
  build:
    working_directory: ~/hex-game-client
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Compile
          command: yarn tsc
      - run:
          name: Build
          command: yarn build

  deploy-live:
    working_directory: ~/hex-game-client
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Upload files
          command: |
            scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./out/* root@hexarena.io:~/hexarena/live/hex-game-client/

  deploy-dev:
    working_directory: ~/hex-game-client
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Upload files
          command: |
            scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./out/* root@hexarena.io:~/hexarena/dev/hex-game-client/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - develop

      - deploy-live:
          filters:
            branches:
              only: master

      - deploy-dev:
          filters:
            branches:
              only: develop
