version: 2
jobs:
  deploy-live:
    working_directory: ~/hexarena-fe
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Upload files
          command: |
            scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null . root@hexarena.io:~/hexarena/live/hexarena-fe
      - run:
          name: Install dependencies
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@hexarena.io "cd ~/hexarena/live/hexarena-fe && yarn"
      - run:
          name: Build
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@hexarena.io "cd ~/hexarena/live/hexarena-fe && yarn build"
      - run:
          name: Reload
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@hexarena.io "pm2 reload live-hexarena-fe"
      - run:
          name: Fetch website
          command: curl http://hexarena.io

  deploy-dev:
    working_directory: ~/hexarena-fe
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Upload files
          command: |
            scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null . root@hexarena.io:~/hexarena/dev/hexarena-fe
      - run:
          name: Install dependencies
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@hexarena.io "cd ~/hexarena/dev/hexarena-fe && yarn"
      - run:
          name: Build
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@hexarena.io "cd ~/hexarena/dev/hexarena-fe && yarn build"
      - run:
          name: Reload
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@hexarena.io "pm2 reload dev-hexarena-fe"
      - run:
          name: Fetch website
          command: curl http://dev.hexarena.io

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-live:
          filters:
            branches:
              only: master
      - deploy-dev:
          filters:
            branches:
              only: develop
